export type DesignDetailsObj = {
    id: number;
    title:string;
    subtitle:string;
    role:string;
    tasks:string;
    tasks2:string;
    listTitle1:string;
    listTitle2:string;
    listTitle3:string;
    listTitle4:string;
    list1:string;
    list2:string;
    list3:string;
    list4:string;
    date:string;
    bannerImg:string;
    bannerThumbnail:string;
    subtitle1:string;
    paragraph1:string;
    image1:string;
    subtitle2:string;
    paragraph2:string;
    image2:string;
    subtitle3:string;
    paragraph3:string;
    image3:string;
    subtitle4:string;
    paragraph4:string;
    image4:string;
    image5:string,
    image6:string,
}